In [175]:
## IMPORTSimport pandas as pdimport numpy as npfrom sklearn.svm import SVCfrom sklearn.model_selection import GridSearchCV# visualizationimport seaborn as snsimport matplotlib.pyplot as plt

## Task 'A'

In [176]:
crash = pd.read_csv('crash.csv', index_col=0)crash.head()

,PassengerId,Survived,Class,Name,Sex,Age,Ticket Price,Safety
0,1,Didn't Survive,Economy,"Braund, Mr. Owen Harris",male,22.0,7.2500,0.336957
1,2,Survived,First Class,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,0.553571
2,3,Survived,Economy,"Heikkinen, Miss. Laina",female,26.0,7.9250,0.336957
3,4,Survived,First Class,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,0.336957
4,5,Didn't Survive,Economy,"Allen, Mr. William Henry",male,35.0,8.0500,0.336957

In [177]:
crash.dtypes

PassengerId       int64
Survived         object
Class            object
Name             object
Sex              object
Age             float64
Ticket Price    float64
Safety          float64
dtype: object

In [178]:
total = crash.isnull().sum().sort_values(ascending=False)percent = (crash.isnull().sum() / crash.isnull().count()).sort_values(ascending=False)missing_data = pd.concat([total, percent], axis=1, keys=["Total", 'Percent'])missing_data

              Total   Percent
Age             177  0.198653
Safety            2  0.002245
PassengerId       0  0.000000
Survived          0  0.000000
Name              0  0.000000
Class             0  0.000000
Sex               0  0.000000
Ticket Price      0  0.000000

to fill the missing 'age' data, we can just fill it with either the 'mean' or the 'median' of the non-missing ones.

im going with the 'mean'

In [179]:
crash['Age'] = crash['Age'].fillna(crash['Age'].mean())

In [180]:
total = crash.isnull().sum().sort_values(ascending=False)percent = (crash.isnull().sum() / crash.isnull().count()).sort_values(ascending=False)missing_data = pd.concat([total, percent], axis=1, keys=["Total", 'Percent'])missing_data

              Total   Percent
Safety            2  0.002245
PassengerId       0  0.000000
Class             0  0.000000
Survived          0  0.000000
Name              0  0.000000
Sex               0  0.000000
Age               0  0.000000
Ticket Price      0  0.000000